services:
  creative-dev:
    build: .
    ports: 
      - 5003:5003
    volumes:
      - ./app:/app
    environment: 
      - FLASK_ENV=development
    restart: unless-stopped
    command: "python /app/app.py"